# Generated by Django 2.1 on 2018-10-17 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=180)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CashInBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LoansReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('amountApplied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loanType', models.CharField(max_length=20)),
                ('modeOfPayment', models.CharField(max_length=15)),
                ('termsOfPaymentYear', models.PositiveIntegerField(default=0)),
                ('termsOfPaymentMonth', models.PositiveIntegerField(default=0)),
                ('interestRate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('methodOfInterest', models.CharField(max_length=10)),
                ('serviceFee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penaltyRate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentToAccountReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name='Document Date')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.AccountReceivable')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=180)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(verbose_name='Entry Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
                ('nameOfTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.Accounts')),
            ],
        ),
        migrations.AddField(
            model_name='servicefee',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='sales',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='paymenttoaccountreceivable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='loansreceivable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.LoansReceivable'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='cashonhand',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='cashinbank',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
    ]
