# Generated by Django 2.1 on 2018-09-06 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Document Date')),
                ('cashVoucherNumber', models.PositiveIntegerField()),
                ('payee', models.CharField(max_length=180)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LoansPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Issued')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountreceivable',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='account_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entry Date'),
            preserve_default=False,
        ),
    ]
