# Generated by Django 2.1 on 2018-10-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20181017_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansreceivable',
            name='termsOfPaymentDay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
