# Generated by Django 2.1 on 2018-09-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('entry', '0003_auto_20180918_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=180)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(verbose_name='Entry Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client')),
                ('nameOfTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Accounts')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountreceivableentry',
            name='account_receivable',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='client',
        ),
        migrations.RenameField(
            model_name='accountreceivable',
            old_name='soldTo',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='accountreceivable',
            name='particulars',
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='AccountReceivableEntry',
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.AddField(
            model_name='sales',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='transaction_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
    ]
