# Generated by Django 2.1 on 2018-10-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20180919_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreceivable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='nameOfTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.Accounts'),
        ),
    ]
