# Generated by Django 2.1 on 2018-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20181001_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreceivable',
            name='date',
            field=models.DateField(verbose_name='Document Date'),
        ),
    ]
