# Generated by Django 2.1 on 2018-10-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20181001_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
    ]
