# Generated by Django 2.1 on 2018-10-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_paymenttoaccountreceivable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
