# Generated by Django 2.1 on 2018-10-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('entry', '0010_auto_20181004_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions')),
            ],
        ),
    ]
