# Generated by Django 2.1 on 2018-10-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_cashinbank_cashonhand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountreceivable',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='cashinbank',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='cashonhand',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='paymenttoaccountreceivable',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
