# Generated by Django 2.1 on 2018-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_auto_20181010_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttoaccountreceivable',
            name='documentNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
