# Generated by Django 2.1 on 2018-10-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_auto_20181013_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreceivable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
        migrations.AlterField(
            model_name='paymenttoaccountreceivable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions'),
        ),
    ]
