# Generated by Django 2.1 on 2018-10-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('entry', '0015_auto_20181013_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Document Date')),
                ('documentNumber', models.PositiveIntegerField()),
                ('loanee', models.CharField(max_length=180)),
                ('loanAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loanType', models.CharField(max_length=20)),
                ('modeOfPayment', models.CharField(max_length=15)),
                ('termsOfPayment', models.PositiveIntegerField()),
                ('interestRate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('methodOfInterest', models.CharField(max_length=10)),
                ('serviceFee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penaltyRate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Transactions')),
            ],
        ),
    ]
